server:
  port: 8787


spring:
 datasource:
  url: jdbc:mysql://localhost:3306/orderconsumerdb
  driver-class-name: com.mysql.cj.jdbc.Driver
  username: root
  password: root
 jpa:
  hibernate.ddl-auto: update
  properties:
    hibernate:
    dialect: org.hibernate.dialect.MySQL8Dialect
    
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
   
jsonorder:
    rabbitmq:
      exchange: jsonorder.exchange
      queue: jsonorder.queue
      routingkey: jsonorder.routingkey
      
xmlorder:
    rabbitmq:
      exchange: xmlorder.exchange
      queue: xmlorder.queue
      routingkey: xmlorder.routingkey

    